### ISSUE TITLE
Improving the Design And creating the  project more attractive for the viewers

### ISSUE THREAD

**Issue by Vijay263601** [BigbabeeSmallbabee/ProjectBFSDFHQ#2]
We can remove the lines seperatig diffrent lines as many lines together are looking odd.. and we can use padding,  background styles like stuff .... and also add an animation to the left and right sides where there is free space... This can make its design attractive ...

we can also use flexboxes and many more such features

**Comment by Jay-study-nildana** [comment]
@Vijay263601 

There are many ways you can do this.

1. You can fork the existing front end app project. (not recommended if you want to do too many changes)
1. You can create a brand new project. add all of us in your private github repo. Then, if it's good, then, we can add it to the list of open source projects. 

Once you have built something, update this thread. Thanks. 

Jay

**Comment by Jay-study-nildana** [comment]
@Vijay263601 

Aha. excellent. I will check it out, and keep you posted. Thanks for continuing to contribute. 

Jay.

**Comment by Jay-study-nildana** [comment]
@Vijay263601 

I like the scrolling animation. Awesome. Can we do some extra stuff like

1. add some gap between the buttons on the top. Right now they are too close?
1. there is a sentence called "DATE WILL COME HERE" just below that beautiful girl's legs. we can remove that sentence.
1. and since you are actively contribution, after "Primary Developer [Jay (Vijayasimha BR) Coding Tutor](https://github.com/Jay-study-nildana)", please add, "Secondary Developer" and your github details, so people know about you also. 

As usual, no urgent. Do these things when you can. and update this thread. 

Jay

**Comment by Vijay263601** [comment]
here i made changes as askked by you @Jay-study-nildana :

https://github.com/Vijay263601/ProjectBFSDFHQFrontEndVanillaJS-main

**Comment by Jay-study-nildana** [comment]
@Vijay263601 

morning. ah. I will check it out and update the thread.

**Comment by Jay-study-nildana** [comment]
@Vijay263601 

when improving the code, update the original fork. Otherwise, you won't be able to create a pull request my friend. and then it won't added to the main organization.

Most importantly, you won't get any credit for the work done.

So, see if you can

1. Fork the original project from the github org.
1. Copy paste your files

and then let me know.

Meanwhile, I am very curious, why instead of updating the repository that you showed me yesterday, why suddenly, today you are using a new repository.

My mind is confused with your behavior. I would love to know why you did this way, so that I can understand why and how your brain worked like this.

Thanks.

Jay.

**Comment by Vijay263601** [comment]
Here I forked the project again @Jay-study-nildana    ...

:-https://github.com/Vijay263601/ProjectBFSDFHQFrontEndVanillaJS

Nothing in particular in creating a new repository, its just that i directly commited the project via vs code.... & then i thout why to copy paste.. it'll takee more time so i directly copied link and shared it to you..

nothing else in particular

**Comment by Jay-study-nildana** [comment]
@Vijay263601 

Unless you 'forked' it, it won't help us. So, please remember to fork. Thanks.

I will check it out and update you. 

Jay.

**Comment by Jay-study-nildana** [comment]
@Vijay263601 

It's perfect. 

When you are ready, create a pull request and I will approve it. 

I am also inviting you to the github organization.  more details here.

https://github.com/orgs/BigbabeeSmallbabee/discussions/1

Thanks

Jay
